### PR TITLE
Add legiond-cpuset.{service,timer}

### LINKED ISSUE #186: introduce cpu reset timer support
After testing, even if the configuration of ryzenadj was applied correctly at the beginning, after keeping the computer turned on and idle for a while, it will still reset, ryzen-ppd will reset the configuration every 2s to make sure that the configuration is valid, while undervolt's timer is every 30s

### PR DESCRIPTION
**Pull request by st0nie**
close #186 
https://github.com/georgewhewell/undervolt
https://github.com/xsmile/ryzen-ppd/

Referenced the link above

Introduce A timer so user can choose to enable it to make cpu tweaks always work
Otherwise CPU changes may revert after a period of time

CC @MrDuartePT

### CODE REVIEW

**Comment by MrDuartePT** [comment]
Before accept this I will also do some change like update the Readme. Since this is not documented anywhere how it works😂.

**Comment by st0nie** [comment]
> Before accept this I will also do some change like update the Readme. Since this is not documented anywhere how it works😂.

wait , after tesing ,the fancurve also get reset sometimes……
legiond's modifications are unnecessary.
just add a timer to do the reset per 5 minutes

**Comment by st0nie** [comment]
readme updated

CC @MrDuartePT

**Comment by MrDuartePT** [comment]
I don't use cpu tweak at the moment but I can test it

**Comment by MrDuartePT** [comment]
ok test it and works fine

**Pull request merged**
