### PR TITLE
Bash script for kernel patching

### PR DESCRIPTION
**Pull request by ARYN-27**
Wrote a simple bash script to patch the kernel easily.

### CODE REVIEW

**Comment by johnfanv2** [comment]
Great. I will merge it in a weak. Currently, I have not much time.

**Comment by ARYN-27** [comment]
Sure, no problem.

**Comment by ARYN-27** [comment]
> I would like to suggest some modifications:
> 
> ```
> #!/usr/bin/env bash
> #####################
> # Checks for doas, sudo, bat and cat first
> # Runs make ans restarts power-profiles-daemon
> #####################
> lll_kernel_patching() {
> 
>     local privup
>     local catit
> 
>     privup=""
>     catit="cat"
>     # checks if is root to not use sudo or doas
>     if [[ ! "${USER}" ]]; then
>     # checks if doas is installed and use it as default
>         [[ -f /usr/bin/doas ]] && privup="doas" || privup="sudo"
>     fi
>     # check if bat is installed and use it as default
>     [[ -f /usr/bin/bat ]] && catit="/usr/bin/bat --paging never" || catit="/usr/bin/cat"
> 
>     make
>     "${privup}" make install
>     "${privup}" make reloadmodule | tail --lines=5 | ${catit}
>     "${privup}" systemctl restart power-profiles-daemon --no-pager --show-transaction
> 
>     printf "%s %s\n" "Patching done." "$?"
> 
> }
> lll_kernel_patching
> ```

I'll check it out. Thanks.

**Comment by johnfanv2** [comment]
Looks good. I didn't you need to do that so often. Do you want to create a merge request @msmafra ? anything else to add?

**Comment by johnfanv2** [comment]
Looks very good! Thank you very much for the script @ARYN-27  and professional improvements @msmafra .

**Comment by ARYN-27** [comment]
Thanks @johnfanv2 and @msmafra

**Comment by msmafra** [comment]
Thanks @johnfanv2 for LLL. @ARYN-27 thanks for the script

**Pull request merged**
