### PR TITLE
Add missing second slashes in the package_repo

### PR DESCRIPTION
**Pull request by Abrifq**

### CODE REVIEW

**Comment by Rittmeister39** [comment]
thanks @Abrifq ! I suppose I need to wait now until maintainer allows this fix into the repo. then i can install it only, right?

**Comment by Abrifq** [comment]
> I suppose I need to wait now until maintainer allows this fix into the repo. then i can install it only, right?

You can install it directly via the deb files until maintainer accepts this fix.

Get both lenovolegionlinux and darkdetect packages files and install them locallu.

**Comment by Rittmeister39** [comment]
thanks. I try that later.

**Comment by MrDuartePT** [comment]
Well i just need to verify if this file is change when the rpm and deb build if that is the case I need to fix that but thanks for finding this typos

**Comment by MrDuartePT** [comment]
I will accept this but i will also fix the workflow file since is where the problem is.

**Pull request merged**
