### PR TITLE
Added dkms install/remove;fixes

### PR DESCRIPTION
**Pull request by msmafra**
Added dkms install/remove;
Privileged elevation logic fixed;
Updated usage;

### CODE REVIEW

**Comment by johnfanv2** [comment]
The DKMS install and all other commands are already inside the make file in the same folder. Can you move your definitions inside the makefile (without power-profile-deamon) to make it consistent?

**Comment by msmafra** [comment]
> The DKMS install and all other commands are already inside the make file in the same folder. Can you move your definitions inside the makefile (without power-profile-deamon) to make it consistent?

I actually based on the documentation and from this one LenovoLegionLinux/deploy/build-dkms.sh with the intention to add it to the README.md.
I can replicate it on the MakeFile, but I don't know how it works. Will it accept any bash built-in commands besides system ones?

**Comment by johnfanv2** [comment]
The file build-dkms.sh will be removed but has not not deleted yet. The installation of dkms is already in the makefile. You might want to call it from your script. You can run commands in the the makefile like in bash. However, note that each line is usually run in a new bash shell. If you do not want that you can "continue" the line with `\` (see Makefile).

**Comment by msmafra** [comment]
Are there more files that will be removed?
I have started some changes on many of the bash scripts inside the **deploy** and **test** folders. Also, I'm trying to figure out a way to make the _setmyfancurve.sh_ easier (in lack of a better word) to use for testing fan curves.

**Comment by johnfanv2** [comment]
The scripts in deploy are currently only used in the CI pipeline (=github actions). They are scripts and not just commands in the github actions so that they can also be run locally for testing when developing. Note that e.g. the script `load.sh` loads it 20 times. So these are really for testing .

What are your ideas?

**Comment by msmafra** [comment]
Hello
So I'll just add 'sudo/doas make DKMS to the script' and keep the remove DKMS (should I?).
On the case of the other scripts, I'll roll them back.
What I had in mind is making the usage of the setmyfancurve.sh easier, a CLI of sorts, and also try to make SecureBoot easy to enable via script.
BUT, on the case of SecureBoot at least, I can't test because my laptop is not enabling it (trying to make Lenovo solve it, they replace my motherboard and now SecureBoot is not working). The setmyfancurve.sh I'll take a while to get my head around it to make it simple to use.

**Pull request closed without merging**
