### PR TITLE
Convert kernel hwmon interface to use PWM (0-255) intsead of RPM v2

### PR DESCRIPTION
**Pull request by MrDuartePT**
This is the second version from #261

The debug messages will be removed later!

### CODE REVIEW

**Comment by johnfanv2** [comment]
@MrDuartePT Have you encountered any errors in the meantime when using this version?

**Comment by MrDuartePT** [comment]
Nothing is broken if you see #268 the kernel driver now uses pwm (in necessary for the driver to be upstream) if you want to set the fancurve using cli create a profile and use legion-cli (the userspace tool convert rpm to pwm) or just use the gui.

**Comment by kepten** [comment]
@MrDuartePT Hmm, I tried to use the GUI too but it didn't work, so I tried to use the CLI according to the README which instructed me to use such `echo 1600 > /sys/XXX` commands. Is the README outdated?
This is what the GUI shows for me for the current `main` commit:
image

The temperatures are not read correctly. The fan speeds are close to the default (1600, 1700, ...) values but when I try to change them they are overwritten to something different (e.g `1764.71` instead of `1800`). And because the temps are wrong, I couldn't make the fans change their speed according to what I provided. Any idea what's going on?

**Comment by MrDuartePT** [comment]
Yes the readme is outdated for `1600` rpm you should send `40`, intead of 40.8 since pwm only accept integers.

The difference you see in the values is because of the rounding of the pwm value and conversion again to rpm, by default the python rounds off to the nearest lower number,

Also looking at the debug output after and before the pwm PR you only have 3 fan curve points, so the ec_registers are not correct for you model they need to be change. So even this PR didn't exist the fan curve control for you model is still broken.

**Comment by kepten** [comment]
@MrDuartePT I got it, thanks.
How can I debug/figure out the correct ec_registers for my model?
I thought it was supported because I found this PR: https://github.com/johnfanv2/LenovoLegionLinux/issues/23

**Comment by kepten** [comment]
@MrDuartePT 
There are 10 values in custom mode (purple color) when I read the values from HW (unlocked, minifancurve enabled):
image
It's the same if I enable locking (nonetheless if minifancurve is enabled or disabled):
image

There are no values when unlocked and minifancurve is disabled (in custom mode):
image

Now in performance mode (red color):

Unlocked and minifancurve disabled (10 values but I cannot set them, they are defaulting after write to the default value):
image
<details><summary>EC memory hexdump</summary>
<p>

```
cat /sys/kernel/debug/legion/ecmemory | hexdump -C
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 2a 20 00  |.............* .|
00000010  00 00 80 00 05 00 64 05  01 01 06 00 00 00 00 00  |......d.........|
00000020  01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 01 00  |................|
00000040  00 00 00 00 50 01 00 00  00 00 00 00 2d 73 00 00  |....P.......-s..|
00000050  00 00 00 00 00 00 c0 e1  00 07 00 1b 63 00 00 00  |............c...|
00000060  00 80 02 03 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000080  00 00 00 00 08 00 00 00  e0 00 40 00 81 00 00 53  |..........@....S|
00000090  4d 50 00 32 30 32 31 00  4c 32 31 4d 34 50 43 35  |MP.2021.L21M4PC5|
000000a0  00 18 00 8e 00 00 00 61  64 00 00 00 64 25 00 00  |.......ad...d%..|
000000b0  32 2a 26 29 00 00 00 00  02 11 00 00 00 00 01 00  |2*&)............|
000000c0  70 00 83 28 e7 07 0b 45  a0 3c 06 27 83 28 64 00  |p..(...E.<.'.(d.|
000000d0  00 00 00 00 00 00 00 1e  00 00 00 00 00 00 00 00  |................|
000000e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 06 00  |................|
000000f0  03 00 00 00 b2 54 00 00  00 00 00 00 00 00 00 00  |.....T..........|
00000100  82 00 00 04 00 00 05 05  13 32 13 13 31 32 32 32  |.........2..1222|
00000110  00 00 ff ff 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000120  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000130  00 02 2e 2a 03 0c a0 00  32 00 2a 00 00 00 00 27  |...*....2.*....'|
00000140  00 11 13 15 17 1a 1d 1f  22 24 28 2c 00 00 00 00  |........"$(,....|
00000150  00 11 13 14 17 19 1c 1e  22 24 28 2c 00 00 00 00  |........"$(,....|
00000160  05 05 05 05 02 02 02 02  02 02 02 02 00 00 00 00  |................|
*
00000180  29 2d 31 36 4b 4e 50 53  55 58 5b 7f 00 00 00 00  |)-16KNPSUX[.....|
00000190  00 23 2a 2e 34 48 4c 4d  51 52 56 59 00 00 00 00  |.#*.4HLMQRVY....|
000001a0  41 41 41 41 41 41 41 4b  4f 51 54 7f 00 00 00 00  |AAAAAAAKOQT.....|
000001b0  00 3c 3c 3c 3c 3c 3c 3c  47 4e 50 52 00 00 00 00  |.<<<<<<<GNPR....|
000001c0  25 29 2e 7f 7f 7f 7f 7f  7f 7f 7f 7f 00 00 00 00  |%)..............|
000001d0  00 21 26 29 7f 7f 7f 7f  7f 7f 7f 7f 00 00 00 00  |.!&)............|
000001e0  00 00 00 00 00 00 32 00  2a 00 00 00 00 00 00 00  |......2.*.......|
000001f0  00 00 07 03 00 00 00 00  00 04 00 00 15 14 18 18  |................|
00000200  15 14 00 00 00 00 00 00  00 00 00 00 00 04 00 00  |................|
00000210  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000220  00 00 00 00 00 00 00 39  00 00 00 00 84 28 00 00  |.......9.....(..|
00000230  00 00 00 03 03 00 02 21  21 00 00 00 00 03 00 01  |.......!!.......|
00000240  00 00 00 00 00 00 00 00  00 00 02 00 00 00 00 00  |................|
00000250  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000260  58 32 58 50 32 35 4a 30  31 5a 37 00 00 00 00 00  |X2XP25J01Z7.....|
00000270  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000002b0  9c 00 70 00 00 00 00 00  00 00 00 00 00 00 00 00  |..p.............|
000002c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000002f0  00 00 00 00 00 00 00 00  00 00 00 00 3d 03 00 00  |............=...|
00000300

```

</p>
</details> 

Unlocked, minifancurve enabled (only 3 values):
image
<details><summary>EC memory hexdump</summary>
<p>

```
cat /sys/kernel/debug/legion/ecmemory | hexdump -C
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 2b 21 00  |.............+!.|
00000010  00 00 80 00 05 00 64 05  01 01 06 00 00 00 00 00  |......d.........|
00000020  01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 01 00  |................|
00000040  00 00 00 00 50 01 00 00  00 00 00 00 2d 73 00 00  |....P.......-s..|
00000050  00 00 00 00 00 00 c0 e1  00 07 00 1b 63 00 00 00  |............c...|
00000060  00 80 02 03 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000080  00 00 00 00 08 00 00 00  e0 00 40 00 81 00 00 53  |..........@....S|
00000090  4d 50 00 32 30 32 31 00  4c 32 31 4d 34 50 43 35  |MP.2021.L21M4PC5|
000000a0  00 18 00 8e 00 00 00 61  64 00 00 00 64 25 00 00  |.......ad...d%..|
000000b0  32 2b 27 2a 00 00 00 00  02 11 00 00 00 00 01 00  |2+'*............|
000000c0  70 00 83 28 e7 07 0b 45  a0 3c 06 27 83 28 64 00  |p..(...E.<.'.(d.|
000000d0  00 00 00 00 00 00 00 1e  00 00 00 00 00 00 00 00  |................|
000000e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 06 00  |................|
000000f0  03 00 00 00 b2 54 00 00  00 00 00 00 00 00 00 00  |.....T..........|
00000100  82 00 00 04 00 00 05 05  13 32 13 13 31 32 32 32  |.........2..1222|
00000110  00 00 ff ff 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000120  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000130  00 02 2e 2a 03 0c 04 00  32 00 2b 00 00 00 00 27  |...*....2.+....'|
00000140  00 10 12 14 16 19 1c 1e  21 23 28 2c 00 00 00 00  |........!#(,....|
00000150  00 10 12 14 16 18 1b 1d  21 23 28 2c 00 00 00 00  |........!#(,....|
00000160  05 05 05 05 02 02 02 02  02 02 02 02 00 00 00 00  |................|
*
00000180  29 2d 31 36 4b 4e 50 53  55 58 5b 7f 00 00 00 00  |)-16KNPSUX[.....|
00000190  00 23 2a 2e 34 48 4c 4d  51 52 56 59 00 00 00 00  |.#*.4HLMQRVY....|
000001a0  41 41 41 41 41 41 41 4b  4f 51 54 7f 00 00 00 00  |AAAAAAAKOQT.....|
000001b0  00 3c 3c 3c 3c 3c 3c 3c  47 4e 50 52 00 00 00 00  |.<<<<<<<GNPR....|
000001c0  25 29 2e 7f 7f 7f 7f 7f  7f 7f 7f 7f 00 00 00 00  |%)..............|
000001d0  00 21 26 29 7f 7f 7f 7f  7f 7f 7f 7f 00 00 00 00  |.!&)............|
000001e0  00 00 00 00 00 00 32 00  2b 00 00 00 00 00 00 00  |......2.+.......|
000001f0  00 00 07 03 00 00 00 00  00 04 00 00 14 14 30 30  |..............00|
00000200  14 14 00 00 00 00 00 00  00 00 00 00 00 04 00 00  |................|
00000210  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000220  00 00 00 00 00 00 00 39  00 00 00 00 84 28 00 00  |.......9.....(..|
00000230  00 00 00 03 03 00 02 21  21 00 00 00 00 00 00 01  |.......!!.......|
00000240  00 00 00 00 00 00 00 00  00 00 02 00 00 00 00 00  |................|
00000250  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000260  58 32 58 50 32 35 4a 30  31 5a 37 00 00 00 00 00  |X2XP25J01Z7.....|
00000270  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000002b0  9c 00 70 00 00 00 00 00  00 00 00 00 00 00 00 00  |..p.............|
000002c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000002f0  00 00 00 00 00 00 00 00  00 00 00 00 3d 03 00 00  |............=...|
00000300


```
</p>
</details> 

Locked, minifancurve enabled (only 3 values):
image

<details><summary>EC memory hexdump</summary>
<p>

```
cat /sys/kernel/debug/legion/ecmemory | hexdump -C
00000000  00 00 00 00 00 00 11 00  00 00 00 00 00 2b 21 00  |.............+!.|
00000010  00 00 80 00 05 00 64 05  01 01 06 00 00 00 00 00  |......d.........|
00000020  01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 01 00  |................|
00000040  00 00 00 00 50 01 00 00  00 00 00 00 2d 73 00 00  |....P.......-s..|
00000050  00 00 00 00 00 00 c0 e1  00 07 00 1b 63 00 00 00  |............c...|
00000060  00 80 02 03 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000080  00 00 00 00 0b 00 00 00  e0 00 40 00 81 00 00 53  |..........@....S|
00000090  4d 50 00 32 30 32 31 00  4c 32 31 4d 34 50 43 35  |MP.2021.L21M4PC5|
000000a0  00 18 00 8e 00 00 00 61  64 00 00 08 64 25 00 00  |.......ad...d%..|
000000b0  33 2a 26 2a 00 00 00 00  02 11 00 00 00 00 01 00  |3*&*............|
000000c0  70 00 83 28 e7 07 0a 45  a0 3c 06 27 83 28 64 00  |p..(...E.<.'.(d.|
000000d0  00 00 00 00 00 00 00 1f  00 00 00 00 00 00 00 00  |................|
000000e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 06 00  |................|
000000f0  03 00 00 00 b2 54 00 00  00 00 00 00 00 00 11 00  |.....T..........|
00000100  82 00 00 04 00 00 05 05  13 32 13 13 31 32 32 32  |.........2..1222|
00000110  00 00 ff ff 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000120  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000130  00 01 2e 2a 00 04 04 00  33 00 2a 00 00 00 00 27  |...*....3.*....'|
00000140  00 0f 11 14 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000160  05 05 05 05 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000180  29 2d 31 36 00 00 00 00  00 00 00 00 00 00 00 00  |)-16............|
00000190  00 23 2a 2e 00 00 00 00  00 00 00 00 00 00 00 00  |.#*.............|
000001a0  41 41 41 41 00 00 00 00  00 00 00 00 00 00 00 00  |AAAA............|
000001b0  00 3c 3c 3c 00 00 00 00  00 00 00 00 00 00 00 00  |.<<<............|
000001c0  25 29 2e 7f 00 00 00 00  00 00 00 00 00 00 00 00  |%)..............|
000001d0  00 21 26 29 00 00 00 00  00 00 00 00 00 00 00 00  |.!&)............|
000001e0  01 07 e3 06 11 11 30 00  2a 00 00 00 00 00 00 00  |......0.*.......|
000001f0  00 00 07 03 00 00 00 00  00 04 00 00 11 11 00 00  |................|
00000200  11 11 00 00 00 00 00 00  00 00 00 00 00 04 00 00  |................|
00000210  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000220  00 00 00 00 00 00 00 39  00 00 00 00 84 28 00 00  |.......9.....(..|
00000230  00 00 00 03 00 00 00 21  21 00 00 00 00 00 00 02  |.......!!.......|
00000240  00 00 00 00 00 00 00 00  00 00 02 00 00 00 00 00  |................|
00000250  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000260  58 32 58 50 32 35 4a 30  31 5a 37 00 00 00 00 00  |X2XP25J01Z7.....|
00000270  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000002b0  9c 00 70 00 00 00 00 00  00 00 00 00 00 00 00 00  |..p.............|
000002c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000002f0  00 00 00 00 00 00 00 00  00 00 00 00 3d 03 00 00  |............=...|
00000300

```
</p>
</details> 

Don't know if it matters but I changed (fixed) the ec_id and base address to match my hw:
```
diff --git a/kernel_module/legion-laptop.c b/kernel_module/legion-laptop.c
index 227588e..ddbd364 100644
--- a/kernel_module/legion-laptop.c
+++ b/kernel_module/legion-laptop.c
@@ -744,9 +744,9 @@ static const struct model_config model_hacn = {
 
 static const struct model_config model_k9cn = {
        .registers = &ec_register_offsets_v0,
-       .check_embedded_controller_id = false,
-       .embedded_controller_id = 0x8227,
-       .memoryio_physical_ec_start = 0xC400, // or replace 0xC400 by 0x0400  ?
+       .check_embedded_controller_id = true,
+       .embedded_controller_id = 0x5507,
+       .memoryio_physical_ec_start = 0xC400,
        .memoryio_size = 0x300,
        .has_minifancurve = true,
        .has_custom_powermode = true,
@@ -757,7 +757,7 @@ static const struct model_config model_k9cn = {
        .access_method_fancurve = ACCESS_METHOD_EC,
        .access_method_fanfullspeed = ACCESS_METHOD_WMI,
        .acpi_check_dev = true,
-       .ramio_physical_start = 0xFE00D400,
+       .ramio_physical_start = 0xFE0B0400,
        .ramio_size = 0x600
 };
 ```

**Pull request merged**
