### PR TITLE
DKMS and Packman Hook

### PR DESCRIPTION
**Pull request by MrDuartePT**
This patch add a script to build a module as dkms package and pacman hook for the arch user.
This will be added to the aur package soon
@johnfanv2 verify the patch pls

### CODE REVIEW

**Comment by MrDuartePT** [comment]
@johnfanv2 dont merge it for now for some reason git deleted dkms.conf

**Comment by MrDuartePT** [comment]
@johnfanv2 dont merge it for now for some reason git deleted dkms.conf

**Comment by MrDuartePT** [comment]
In the pull request #38 I have a script to install the dkms package automatic.

**Comment by johnfanv2** [comment]
Thanks for the great work, @MrDuartePT , also on #35 !

 Just a few changes are needed in my opinion:
* Currently, this breaks the CI/CD pipeline (see failed checks above) because the build.sh is called in the CI from the LenovoLegionLinux folder, as seen above. You can fix that by removing "cd .." again or using the following
```bash
# Get the folder where the script is saved
DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "${DIR}/../kernel_module"
```
* Does this update the DKMS module if new code from github is pulled and the install script is rerun?
* Could you put the DKMS install steps into the Makefile in kernel_module, where usual install 'script' is located?

**Comment by MrDuartePT** [comment]
The dkms updates if the script is rerun basically removes and reinstall the dkms module.
The makefile part i can do it later

**Comment by MrDuartePT** [comment]
Done you can install the dkms using `sudo make dkms`

**Comment by MrDuartePT** [comment]
lgtm, lets go update the aur package

**Pull request merged**
