### PR TITLE
Added installation via DKMS

### PR DESCRIPTION
**Pull request by lrmpsm53**

### CODE REVIEW

**Comment by johnfanv2** [comment]
Great! Thanks alot. DKMS was always a feature that I wanted to integrate.

**Comment by lrmpsm53** [comment]
If you mean manual testing on my machine, then it works for me.

**Comment by lrmpsm53** [comment]
Hm. Now updated the kernel. I saw such an error. What do you think?
Fedora 37

[   10.569575] legion_laptop: module verification failed: signature and/or required key missing - tainting kernel

**Comment by lrmpsm53** [comment]
To test things like this, I disabled secure boot. Signing through the MOK is something worth trying.

**Comment by johnfanv2** [comment]
Maybe the steps taken here may help: https://github.com/lwfinger/rtw89

I would be important that one can update the DKMS module after one has pulled new code from github and make the changes mentioned above.

**Comment by lrmpsm53** [comment]
I solved the problem with secure boot by adding MOK. https://github.com/dell/dkms#secure-boot

**Comment by MrDuartePT** [comment]
Be real I use secure boot and my dkms modules are sign when I rebuild the initframs with dracut. If someone is using secure boot in there setup the should know how to setup dkms to sign the modules. I will advice remove the line about secure boot from the readme.

**Comment by MrDuartePT** [comment]
In the pull request #38 I have a script to install the dkms package automatic.

**Comment by MrDuartePT** [comment]
When I get home I will review your code and merge it and the just make a change to dkms.conf.

**Comment by lrmpsm53** [comment]
@MrDuartePT  Got you

**Comment by lrmpsm53** [comment]
@MrDuartePT  I also note that I did not use the IOC keys from Fedor. DCMS generates its own keys.

**Comment by MrDuartePT** [comment]
@lrmpsm53 when you can test the new changing to dkms on your machine just to see if still work to you.

**Comment by lrmpsm53** [comment]
Today after work

**Pull request merged**
