### PR TITLE
Create PKGBUILD

### PR DESCRIPTION
**Pull request by MrDuartePT**
I create PKGBUILD for arch i will put in the AUR.
I dont have problems in maintain myself.

### CODE REVIEW

**Comment by johnfanv2** [comment]
Thanks a lot @MrDuartePT. This looks great. I am not sure how to best install the Python stuff in Arch. I already tried a few things on Ubuntu.

- I already created a Python package. There is a install script that uses the python package. https://github.com/johnfanv2/LenovoLegionLinux/blob/main/deploy/build_python.sh. But I guess it might be better to manage all these files in the Arch way.
- There is also a .desktop file. The GUI has to run as root, so maybe start it with pkexec, so I used pkexec. It also needs a policy file to run a GUI app. Currently, both files assume the Python package, so it starts without ".py" extension. I guess that has to change if you do not want to use the python package. But I would be happy if you change it and confirm that it works.

**Comment by MrDuartePT** [comment]
The arch way is particually the same way that use pip probably I just to do a few changes to your script or nothing at all

**Comment by johnfanv2** [comment]
Good idea.

**Comment by MrDuartePT** [comment]
Sorry for the mess now its working you can merge

**Comment by MrDuartePT** [comment]
I detect that the Lenovo_gui module is not installing correctly I will see tomorrow I don't have head for that today.

**Comment by MrDuartePT** [comment]
Tomorrow I will implement only the reload module after isntall and after I will try to solve the Python problem.

**Comment by MrDuartePT** [comment]
Now is full working including the python gui and cli app

**Comment by MrDuartePT** [comment]
Now is full working i have to use pip when installing to force to install the dependencies now i just have to see if will be accept on the AUR.

image

image

Note: the .dektop file work on X11 on Wayland is problem with my xhost configuration

**Comment by johnfanv2** [comment]
Thanks for all the packaging work. I added you as a collaborator to the repository. I assume that you have to accept it. I hope that you can then merge it yourself. I added you because I guess you would have to do small fixes until it works in the AUR. And I will not have much time the next weeks to always merge small changes. Please let me know if something does not work.

I am not sure if you have to create a master branch for AUR or if it works with main.

**Pull request merged**
