### PR TITLE
Swap the dark and light logos

### PR DESCRIPTION
**Pull request by brainos233**
Swap `legion_logo_dark.png` and `legion_logo_light.png`, because the white icon is more suitable for the dark theme, while the black icon is more suitable for the light theme.

<details><summary>Before change</summary>
<p>

image

</p>
</details> 

<details><summary>After change</summary>
<p>

image

</p>
</details>

### CODE REVIEW

**Comment by rozwell** [comment]
IMHO it's a code typo, because I named these icons based on what they are, not in which theme they will be used ;)

If theme is supposed to be the main determinant, then we shall rename these logos to something like `dark_theme_logo.png` & `light_theme_logo.png` to make more sense.

**Comment by brainos233** [comment]
> IMHO it's a code typo, because I named these icons based on what they are, not in which theme they will be used ;)
> 
> If theme is supposed to be the main determinant, then we shall rename these logos to something like `dark_theme_logo.png` & `light_theme_logo.png` to make more sense.

Well, I think using `dark`, `light` as a suffix is better than a prefix.

**Comment by rozwell** [comment]
> Well, I think using `dark`, `light` as a suffix is better than a prefix.
Minor semantics ;)

**Comment by johnfanv2** [comment]
I guess these are good points. This definitely needs a change. The only problem I see that in standard Ubuntu/Gnome the system tray is black in both dark mode and light mode.

What is the color of the the system tray on your distros in both modes?

**Comment by rozwell** [comment]
> I guess these are good points. This definitely needs a change. The only problem I see is that in standard Ubuntu/Gnome the system tray is black in both dark mode and light mode.
> 
> What is the color of the the system tray on your distros in both modes?

On Kubuntu it's all normal here:
- light theme uses dark icons
- dark theme uses light icons

**Comment by MrDuartePT** [comment]
ok i will do the change and all create a new release

**Comment by MrDuartePT** [comment]
This create problem on dark background I will revert this

**Comment by rozwell** [comment]
@MrDuartePT is there an option to manually switch between these icons?

**Comment by MrDuartePT** [comment]
I think not @johnfanv2 how much is difficult to add that?

**Comment by MrDuartePT** [comment]
I will revert this for now just to not break in other system

**Comment by rozwell** [comment]
@johnfanv2 let us know if & when you'll start working on this, cause I might have a little time to do that myself ;)

**Comment by MrDuartePT** [comment]
@rozwell you can make and submit a PR

**Comment by MrDuartePT** [comment]
I gonna verify one thing to see if a really need to revert this.

**Comment by rozwell** [comment]
> The only problem I see is that in standard Ubuntu/Gnome the system tray is black in both dark mode and light mode.

I initially made white icon with a little shadow so it would work well on any background, but these icons are to small for that and it was not looking good.


> @rozwell you can make and submit a PR

I can once I'll have some time to spare, but that could take a few days 😐

**Comment by MrDuartePT** [comment]
No problem😀

**Comment by MrDuartePT** [comment]
I found out the problem in Kubuntu and Ubuntu the tray are dark but the system GTK theme is set to light @brainos233 make a good observation our system the way there are setup is not right

**Comment by johnfanv2** [comment]
You can now set the color of the logo in the settings to a fixed scheme or change automatically. Please check if it works on your distro.

**Comment by MrDuartePT** [comment]
I can confirm it works

**Pull request merged**
