### PR TITLE
Update acpi events

### PR DESCRIPTION
**Pull request by st0nie**
Signed-off-by: ston <ston.jia@outlook.com>

### CODE REVIEW

**Comment by st0nie** [comment]
CC @MrDuartePT

**Comment by MrDuartePT** [comment]
Was think doing the same. Thanks

**Comment by MrDuartePT** [comment]
GitHub change something the tag deb build and kernel config is broken

**Comment by MrDuartePT** [comment]
Well I will add another tag and bump to 0.0.15. Just to have new debs for Ubuntu

**Pull request merged**
